server:
  port: 8080
admin:
  username: admin
  password: admin
  email: admin@gmail.com
api-prefix: /api/v1
spring:
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/dlearning?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: vovannghiahiep1562003@gmail.com
    password: zuvzquhzgbnmvqqi

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secretKey: 90c85b588e8d468d45cf5a70a5517dc6507a0655d7ea0664f6eb70dd4d76394e
  valid-duration: 86400
  refresh-duration: 86400

cloudinary:
  cloud_name: dqnwxejgy
  api_key: 486184719822545
  api_secret: XOtBNDM_B6EzTK9TUQ9ET1CBDHA

upload-file:
  base-uri: file:/path/to/upload/

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    hashSecret: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-callback
    version: 2.1.0
    command: pay
    order_type: others